sudo: required
language: node_js
branches:
  only:
  - develop
services:
  - docker
node_js:
  - "9"
install:
    - yarn
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
script:
    - GIT_HEAD="$(git rev-parse --short HEAD)"
    - eval ${DOCKER_LOGIN}
    - aws ecs update-service --region $AWS_REGION --cluster $AWS_ECS_CLUSTER_NAME --service $DOCKER_IMAGE_NAME --force-new-deployment --query 'service.serviceName'
    - docker build --no-cache -t $DOCKER_IMAGE_NAME:latest -t $DOCKER_IMAGE_NAME:$GIT_HEAD --build-arg GIT_HEAD=$GIT_HEAD .
    - docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_URL:latest
    - docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_URL:$GIT_HEAD
    - docker push $DOCKER_IMAGE_URL:latest
    - docker push $DOCKER_IMAGE_URL:$GIT_HEAD