sudo: required
language: node_js
branches:
  only:
  - develop
services:
  - docker
node_js:
  - "9"
install:
    - yarn
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
script:
    - GIT_HEAD="$(git rev-parse --short HEAD)"
    - eval ${DOCKER_LOGIN}
    - docker build --no-cache -t $DOCKER_IMAGE_NAME:latest -t $DOCKER_IMAGE_NAME:$GIT_HEAD --build-arg GIT_HEAD=$GIT_HEAD .
    - docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_URL:latest
    - docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_URL:$GIT_HEAD
    - docker push $DOCKER_IMAGE_URL:latest
    - docker push $DOCKER_IMAGE_URL:$GIT_HEAD
    - aws cloudformation update-stack --region $AWS_REGION --stack-name $DOCKER_IMAGE_NAME --use-previous-template --parameters ParameterKey=ImageTag,ParameterValue=$GIT_HEAD