sudo: required
language: node_js
branches:
  only:
  - develop
services:
  - docker
node_js:
  - "9"
install:
  - yarn
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - GIT_HEAD="$(git rev-parse --short HEAD)"
  - eval ${DOCKER_LOGIN}
  - docker build --no-cache -t $DOCKER_IMAGE_NAME:latest -t $DOCKER_IMAGE_NAME:$GIT_HEAD --build-arg GIT_HEAD=$GIT_HEAD .
deploy:
  provider: script
  script: ci/deploy.sh
  on:
    branch: "develop"